import type { Metadata } from 'next'
import { Header } from '@/components/Header/Header'
import './globals.css'

export const metadata: Metadata = {
    title: 'Louvores João Pessoa',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-br">
            <body className="transition-all duration-500">
                <noscript>Enable Javascript to use this site!</noscript>
                <Header />
                <div className="flex justify-center mt-4 px-4 mb-4">
                    {children}
                </div>
            </body>
        </html>
    )
}
